version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./config/db-init-postgres.sh:/docker-entrypoint-initdb.d/db-init-postgres.sh
  swagger:
    image: swaggerapi/swagger-ui:v3.25.0
    container_name: swagger
    restart: always
    env_file: .env
    ports:
      - 9999:8080
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    restart: always
    ports:
      - 9998:8080