service:
  type: ClusterIP

config:
  api:
    openid_configuration: https://keycloak/auth/realms/<realm>/.well-known/openid-configuration
    rest:
      host: '0.0.0.0'
      port: 8080
      spec: ./openapi.yaml
      rbac: config/rbac.yaml
      cors:
        allowedOrigins:
          - '*'
        allowedHeaders:
          - Content-Type
          - Sec-Fetch-Dest
          - Referer
          - Accept
          - User-Agent
          - API-KEY
        allowedMethods:
          - OPTIONS
          - GET
          - POST
      jwt:
        pubKey: https://keycloak/auth/realms/<realm>

  datasource:
    type: postgres
    host: <postgres-host>
    port: 5432
    database: <db>
    sslMode: disable
    migrations: db/migrations

extraLabels:
  git_hash: '"00000000"'
image:
  pullPolicy: Always
  repository: harbor.amihan.net/bdo/dafs/product-service
  tag: latest
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,
      User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,
      Authorization,Accept,API-KEY
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, PUT, POST, DELETE, PATCH,
      OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-origin: '*'
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header API-KEY $http_api_key;
  enabled: true
  hosts:
  - host: product-service.bdo.amihan.net
    paths:
    - /
  tls:
  - hosts:
    - product-service.bdo.amihan.net
    secretName: product-service-dev-tls
registries:
- password: ''
  url: harbor.amihan.net
  username: ''
replicaCount: 1