// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"encoding/json"
	"github.com/gorilla/mux"
	"github.com/jinzhu/gorm"
	"github.com/sirupsen/logrus"
	"github.com/spf13/viper"
	"gitlab.com/amihan/core/base.git/internal/component/user"
	"gitlab.com/amihan/core/base.git/internal/entrypoint/api/rest"
	"gitlab.com/amihan/core/base.git/internal/entrypoint/api/rest/base"
	"gitlab.com/amihan/core/base.git/internal/infrastructure/postgres"
	"gitlab.com/amihan/core/base.git/internal/infrastructure/postgres/repository"
	"io/ioutil"
	"os"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func createRestAPI() *rest.API {
	keys := ProvideKeysFromFile()
	config := ProvideRestAPIConfig(keys)
	router := mux.NewRouter()
	datasource := ProvideDatasource(keys)
	db := ProvideGormDB(datasource)
	userRepository := repository.NewGormUserRepository(db)
	service := user.NewUserService(userRepository)
	controller := base.NewController(service)
	api := rest.NewRestAPI(config, router, controller)
	return api
}

func createMigration() *postgres.Migration {
	keys := ProvideKeysFromFile()
	datasource := ProvideDatasource(keys)
	migration := postgres.NewMigration(datasource)
	return migration
}

// wire.go:

// this is where we wire all dependencies to run the API
type Keys struct {
	DBUsername string `json:"db-username"`
	DBPassword string `json:"db-password"`
	APIKey     string `json:"api-key"`
}

func ProvideKeysFromFile() *Keys {
	file := viper.GetString("secrets.file")
	jsonFile, err := os.Open(file)
	if err != nil {
		logrus.WithError(err).Error("unable to read security keys file")
		os.Exit(1)
	}
	defer jsonFile.Close()

	byteValue, _ := ioutil.ReadAll(jsonFile)
	var secrets Keys
	json.Unmarshal(byteValue, &secrets)

	return &secrets
}

func ProvideRestAPIConfig(keys *Keys) *rest.Config {
	var config rest.Config
	err := viper.UnmarshalKey("api.rest", &config)
	if err != nil {
		logrus.WithError(err).Error("unable to read RestAPIConfig")
		os.Exit(1)
	}

	rbacData, err := ioutil.ReadFile(config.Auth.RBACFile)
	if err != nil {
		logrus.WithError(err).Error("Error in reading RBAC data")
	}

	config.Auth.RBAC = string(rbacData)
	config.Auth.APIKey = keys.APIKey

	config.Version = root.Version
	logrus.Info("========================================")
	logrus.Info("API Configuration")
	logrus.Info("========================================")
	logrus.Info("Host:    ", config.Host)
	logrus.Info("Port:    ", config.Port)
	logrus.Info("Spec:    ", config.Spec)
	logrus.Info("Version: ", config.Port)
	logrus.Debugf("API Config: %+v", config)
	level := viper.GetBool("log.debug")
	if level {
		logrus.SetLevel(logrus.DebugLevel)
	}
	return &config
}

func ProvideDatasource(keys *Keys) *postgres.Datasource {
	var datasource postgres.Datasource
	err := viper.UnmarshalKey("datasource", &datasource)
	if err != nil {
		logrus.WithError(err).Error("unable to read Datasource config")
		os.Exit(1)
	}
	datasource.Username = keys.DBUsername
	datasource.Password = keys.DBPassword
	return &datasource
}

func ProvideGormDB(datasource *postgres.Datasource) *gorm.DB {
	db, err := gorm.Open("postgres", datasource.AsPQString())
	if err != nil {
		logrus.WithError(err).Error("unable to get gorm db connection")
		os.Exit(1)
	}
	return db
}
